name: Summarize Merged Pull Requests Action
description: GitHub Action that summarizes merged pull requests
author: gyugyu

branding:
  icon: edit
  color: orange

inputs:
  source_branch:
    description: 'The source branch (e.g., main) whose merged PRs are included.'
    default: 'main'
    required: false
  section_title:
    description: 'Title for the section.'
    default: 'This deploy will include the following PRs'
    required: false
  start_mark:
    description: 'Start marker in PR body.'
    default: '<!-- DEPLOY_DIFF_START -->'
    required: false
  end_mark:
    description: 'End marker in PR body.'
    default: '<!-- DEPLOY_DIFF_END -->'
    required: false
  dry_run:
    description: 'If true, do not update the PR body. (true/false)'
    default: 'false'
    required: false

runs:
  using: node20
  main: dist/index.js

permissions:
  contents: read
  pull-requests: write
